---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - config.aiguard.io
  resources:
  - computesentrypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.aiguard.io
  resources:
  - computesentrypolicies/finalizers
  verbs:
  - update
- apiGroups:
  - config.aiguard.io
  resources:
  - computesentrypolicies/status
  verbs:
  - get
  - patch
  - update
