//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Actions) DeepCopyInto(out *Actions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Actions.
func (in *Actions) DeepCopy() *Actions {
	if in == nil {
		return nil
	}
	out := new(Actions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeSentryPolicy) DeepCopyInto(out *ComputeSentryPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeSentryPolicy.
func (in *ComputeSentryPolicy) DeepCopy() *ComputeSentryPolicy {
	if in == nil {
		return nil
	}
	out := new(ComputeSentryPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeSentryPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeSentryPolicyList) DeepCopyInto(out *ComputeSentryPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComputeSentryPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeSentryPolicyList.
func (in *ComputeSentryPolicyList) DeepCopy() *ComputeSentryPolicyList {
	if in == nil {
		return nil
	}
	out := new(ComputeSentryPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeSentryPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeSentryPolicySpec) DeepCopyInto(out *ComputeSentryPolicySpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	out.SpyConfig = in.SpyConfig
	out.Thresholds = in.Thresholds
	out.EvalConfig = in.EvalConfig
	out.Actions = in.Actions
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeSentryPolicySpec.
func (in *ComputeSentryPolicySpec) DeepCopy() *ComputeSentryPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ComputeSentryPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeSentryPolicyStatus) DeepCopyInto(out *ComputeSentryPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeSentryPolicyStatus.
func (in *ComputeSentryPolicyStatus) DeepCopy() *ComputeSentryPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ComputeSentryPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvalConfig) DeepCopyInto(out *EvalConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvalConfig.
func (in *EvalConfig) DeepCopy() *EvalConfig {
	if in == nil {
		return nil
	}
	out := new(EvalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpyConfig) DeepCopyInto(out *SpyConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpyConfig.
func (in *SpyConfig) DeepCopy() *SpyConfig {
	if in == nil {
		return nil
	}
	out := new(SpyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Thresholds) DeepCopyInto(out *Thresholds) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Thresholds.
func (in *Thresholds) DeepCopy() *Thresholds {
	if in == nil {
		return nil
	}
	out := new(Thresholds)
	in.DeepCopyInto(out)
	return out
}
